---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    app: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: h0tbird/tcp-echo-server:1.2
        imagePullPolicy: IfNotPresent
        args: [ "7070", "{{ .Release.Name }}:" ]
        ports:
        - containerPort: 7070
          name: echo
          protocol: TCP
