---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpbin
  name: httpbin
  namespace: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      # annotations:
      #   sidecar.istio.io/proxyImage: docker.io/h0tbird/proxyv2:1.17.1
      labels:
        app: httpbin
    spec:
      containers:
      - image: h0tbird/httpbin:latest
        name: go-httpbin
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
