---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      # annotations:
      #   sidecar.istio.io/proxyImage: docker.io/h0tbird/proxyv2:1.17.1
      labels:
        app: sleep
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: sleep
        image: nicolaka/netshoot
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
