---
apiVersion: v1
kind: Service
metadata:
  name: nghttpd
  labels:
    app: nghttpd
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    appProtocol: http2
    targetPort: http
  selector:
    app: nghttpd
  type: ClusterIP
