---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-echo
  labels:
    app: tcp-echo
    service: tcp-echo
spec:
  ports:
  - name: tcp
    port: 9000
  - name: tcp-other
    port: 9001
  selector:
    app: tcp-echo