---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin-svc
  namespace: httpbin
spec:
  host: httpbin.httpbin.svc.{ .Values.domain }
  trafficPolicy:
    connectionPool:
      http:
        maxRequestsPerConnection: 10
    loadBalancer:
      simple: ROUND_ROBIN
      localityLbSetting:
        enabled: true
        failover: []
    outlierDetection:
      consecutive5xxErrors: 10
      interval: 1s
      baseEjectionTime: 1m
