---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "{{ .Release.Name }}.demo.lab"
    tls:
      mode: SIMPLE
      credentialName: tls-{{ .Release.Name }}
