---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: httpbin
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "httpbin.{{ .Release.Name }}.demo.lab"
    tls:
      mode: SIMPLE
      credentialName: tls-{{ .Release.Name }}
