---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
spec:
  secretName: tls-{{ .Release.Name }}
  duration: 24h0m0s
  dnsNames:
  - "echo.{{ .Release.Name }}.demo.lab"
  - "httpbin.{{ .Release.Name }}.demo.lab"
  - "nghttpd.{{ .Release.Name }}.demo.lab"
  issuerRef:
    name: ingress-ca
    kind: ClusterIssuer
    group: cert-manager.io
