apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: httpbin
  name: httpbin
  namespace: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpbin
    spec:
      containers:
      - image: mccutchen/go-httpbin:latest
        name: go-httpbin
        resources: {}
status: {}
