apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: httpbin
  name: httpbin
  namespace: httpbin
spec:
  ports:
  - name: 5000-8080
    port: 5000
    protocol: TCP
    targetPort: 8080
  selector:
    app: httpbin
  type: ClusterIP
