---
apiVersion: networking.istio.io/v1beta1
kind: WorkloadGroup
metadata:
  name: httpbin
  namespace: httpbin
spec:
  metadata:
    labels:
      app: httpbin
  template:
    ports:
      http: 8080
    serviceAccount: httpbin
    network: vm-network
    locality: milky-way/solar-system/virt-01
  probe:
    periodSeconds: 5
    initialDelaySeconds: 1
    httpGet:
      port: 8080
      path: /get
