---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: httpbin
  namespace: httpbin
spec:
  metadata:
    labels:
      app: httpbin
  template:
    serviceAccount: default
    network: network0
