---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: echo
spec:
  gateways:
  - {{ .Release.Name }}
  hosts:
  - echo.{{ .Release.Name }}.demo.lab
  http:
  - name: default
    route:
    - destination:
        host: echo.{{ .Release.Namespace }}.svc.{{ .Values.domain }}
        port:
          number: 9000
