---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin
spec:
  gateways:
  - httpbin
  hosts:
  - httpbin.{{ .Release.Name }}.demo.lab
  http:
  - name: default
    route:
    - destination:
        host: httpbin.{{ .Release.Namespace }}.svc.{{ .Values.domain }}
        port:
          number: 80
