---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin
spec:
  gateways:
  - istio-system/ingress-gateway
  hosts:
  - '*'
  http:
  - name: default
    route:
    - destination:
        host: httpbin.httpbin.svc.cluster.local
        port:
          number: 80
