---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin
spec:
  gateways:
  - istio-system/ingress-all
  hosts:
  - {{ .Release.Namespace }}.demo.lab
  http:
  - name: default
    route:
    - destination:
        host: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.{{ .Values.domain }}
        port:
          number: 80
