---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin
spec:
  gateways:
  - ingress-gateway
  hosts:
  - httpbin.demo.com
  http:
  - name: default
    route:
    - destination:
        host: httpbin.demo.com
        port:
          number: 80
