---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin
spec:
  gateways:
  - ingress-gateway
  hosts:
  - '*'
  http:
  - name: default
    route:
    - destination:
        host: httpbin
        port:
          number: 80
